INSERT INTO tb_chef (name, position, income) VALUES
                                                 ('John Doe', 'Head Chef', 50000),
                                                 ('Jane Smith', 'Sous Chef', 45000),
                                                 ('Alice Johnson', 'Pastry Chef', 47000),
                                                 ('Bob Brown', 'Line Cook', 40000),
                                                 ('Carol White', 'Dishwasher', 35000),
                                                 ('David Wilson', 'Prep Cook', 38000),
                                                 ('Emily Harris', 'Chef de Partie', 43000),
                                                 ('Frank Clark', 'Executive Chef', 55000),
                                                 ('Grace Lewis', 'Banquet Chef', 48000),
                                                 ('Hannah Walker', 'Garde Manger', 42000),
                                                 ('Ivy Martinez', 'Breakfast Chef', 41000),
                                                 ('Jack Anderson', 'Kitchen Manager', 46000),
                                                 ('Kathy Thomas', 'Cook', 39000),
                                                 ('Liam Moore', 'Chef Assistant', 37000),
                                                 ('Mia Robinson', 'Grill Cook', 43000),
                                                 ('Nate Lewis', 'Food Prep', 36000),
                                                 ('Olivia Young', 'Steward', 34000),
                                                 ('Paul Lee', 'Catering Chef', 50000),
                                                 ('Quinn King', 'Food Stylist', 44000),
                                                 ('Rachel Scott', 'Sous Chef', 45500);

INSERT INTO tb_department (description, name, chef_id) VALUES
                                                           ('Italian cuisine with a modern twist', 'Italian Kitchen', 1),
                                                           ('French gourmet dining', 'Le Gourmet', 2),
                                                           ('American diner classics', 'Classic Diner', 3),
                                                           ('Asian fusion dishes', 'Asian Delights', 4),
                                                           ('Vegetarian and vegan specialties', 'Green Eats', 5),
                                                           ('Seafood and shellfish', 'Ocean’s Bounty', 6),
                                                           ('Barbecue and grilled meats', 'Smokehouse', 7),
                                                           ('Baking and desserts', 'Sweet Treats', 8),
                                                           ('High-end catering services', 'Elite Catering', 9),
                                                           ('International flavors and spices', 'World Cuisine', 10),
                                                           ('Breakfast and brunch favorites', 'Morning Glory', 11),
                                                           ('Regional American dishes', 'Regional Fare', 12),
                                                           ('Casual dining and comfort food', 'Comfort Corner', 13),
                                                           ('Specialty coffees and light meals', 'Coffee House', 14),
                                                           ('Sushi and Japanese cuisine', 'Sushi Bar', 15),
                                                           ('Mediterranean and Middle Eastern', 'Mediterranean Haven', 16),
                                                           ('Fast food and quick bites', 'Fast Eats', 17),
                                                           ('Traditional dishes from various cultures', 'Cultural Bites', 18),
                                                           ('Gourmet sandwiches and wraps', 'Gourmet Sandwiches', 19),
                                                           ('Fresh salads and light meals', 'Salad Bar', 20);
INSERT INTO tb_worker (name, income, age, position, department_id) VALUES
                                                                       ('Alice Carter', 30000, 25, 'Waiter', 1),
                                                                       ('Brian Davis', 32000, 28, 'Cook', 1),
                                                                       ('Clara Evans', 31000, 30, 'Cashier', 2),
                                                                       ('Daniel Foster', 34000, 32, 'Chef', 2),
                                                                       ('Ella Green', 33000, 27, 'Waitress', 3),
                                                                       ('Frank Harris', 35000, 35, 'Barista', 3),
                                                                       ('Grace Hughes', 36000, 29, 'Sous Chef', 4),
                                                                       ('Henry James', 34000, 31, 'Dishwasher', 4),
                                                                       ('Ivy King', 37000, 33, 'Kitchen Manager', 5),
                                                                       ('Jack Lee', 35000, 26, 'Server', 5),
                                                                       ('Kathy Martin', 34000, 34, 'Prep Cook', 6),
                                                                       ('Leo Nelson', 32000, 28, 'Busser', 6),
                                                                       ('Mia OConnor', 33000, 29, 'Hostess', 7),
                                                                       ('Nate Phillips', 34000, 30, 'Grill Cook', 7),
                                                                       ('Olivia Quinn', 36000, 31, 'Chef', 8),
                                                                       ('Paul Roberts', 37000, 32, 'Dishwasher', 8),
                                                                       ('Quinn Scott', 34000, 26, 'Assistant Chef', 9),
                                                                       ('Rachel Turner', 35000, 28, 'Cook', 9),
                                                                       ('Sam Underwood', 32000, 30, 'Waiter', 10),
                                                                       ('Tina Vance', 33000, 27, 'Server', 10);
